name: 01 - Building Blocks

on: workflow_dispatch


jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Succeeding step
        run: |
          echo "I will succeed"
          exit 0
      - name: Say Goodbye
        run: echo "Goodbye"