name: 03 - Workflow Runners

on: workflow_dispatch

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "I'm running on an Ubuntu runner."
          echo "Runner: ${{ runner.os }} on ${{ runner.arch }}"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        shell: bash
        run: |
          echo "I'm running on a Windows runner."
          echo "Runner: ${{ runner.os }} on ${{ runner.arch }}"
  mac-echo:
    runs-on: macos-latest
    steps:
      - name: Show OS
        shell: bash
        run: |
          echo "I'm running on a Mac runner."
          echo "Runner: ${{ runner.os }} on ${{ runner.arch }}"
