name: 08 - Using Variables

on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "Workflow variable"
  UNDEFINED_VAR_OR_DEFAULT: ${{ vars.UNDEFINED || 'default value' }}

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Job variable"
    steps:
      - name: Print Env variables
        env:
          STEP_VAR: "Step variable"
        run: |
          echo "Step var: $STEP_VAR"
          echo "Job var: $JOB_VAR"
          echo "Workflow var: $WORKFLOW_VAR"

  echo-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print environment
        run: |
          echo "ENVIRONMENT: ${{ vars.ENVIRONMENT }}"

  echo-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Print environment
        run: |
          echo "ENVIRONMENT: ${{ vars.ENVIRONMENT }}"

  echo-undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print undefined variables
        run: |
          echo "Undefined: $UNDEFINED_VAR_OR_DEFAULT"
