name: 09 - Using Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
  print-labels:
    name: Print labels
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.labels != null }}
    steps:
      - name: Print PR labels using join()
        run: |
          echo "PR labels:"
          echo ${{ join(github.event.pull_request.labels.*.name, ', ') }}
      
      - name: Print PR labels using toJSON()
        run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.labels) }}
          EOF
