name: 09 - Using Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
  on-pull-request:
    name: On Pull Request
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add label 'needs-review'
        run: |
          echo "Adding 'needs-review' to PR: ${{ github.event.pull_request.title }}"
          gh pr edit ${{ github.event.pull_request.number }} --add-label "needs-review"
      - name: Is this a bug?
        if: contains(github.event.pull_request.title, 'Fix:')
        run: |
          echo "This is a bug fix"
          gh pr edit ${{ github.event.pull_request.number }} --add-label "bug"

  print-labels:
    name: Print labels
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.labels != null }}
    steps:
      - name: Print PR labels using join()
        run: |
          echo "PR labels:"
          echo ${{ join(github.event.pull_request.labels.*.name, ', ') }}
      
      - name: Print PR labels using toJSON()
        run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.labels) }}
          EOF
