name: 09 - Using Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "PR title: $PR_TITLE"
      - name: Is a bug fix?
        if: ${{ !cancelled() && contains(github.event.pull_request.title, 'Fix:') }}
        run: |
          echo "This is a bug fix"
          gh pr edit ${{ github.event.pull_request.number }} --add-label "bug"

      - name: Print PR labels using join()
        run: |
          echo "PR labels:"
          echo ${{ join(github.event.pull_request.labels.*.name, ', ') }}
      
      - name: Print PR labels using toJSON()
        run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.labels) }}
          EOF

  status-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: exit 1
      - name: On success
        if: success()
        run: echo "Previous step succeeded"
      - name: On failure
        if: failure()
        run: echo "Previous step failed"
      - name: Always (unless cancelled)
        if: ${{ !cancelled() }}
        run: echo "The workflow wasn't cancelled"
      - name: On cancelled
        if: cancelled()
        run: echo "The workflow was cancelled"
