name: 09 - Using Functions

on:
  pull_request:
  workflow_dispatch:

jobs:
  label-pull-request:
    name: Add labels to PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - run: |
          echo "Adding labes to PR: ${{ github.event.pull_request.title }}"
          gh pr edit ${{ github.event.pull_request.number }} --add-label "needs-review"
      - name: Is bug fix?
        if: contains(github.event.pull_request.title, 'Fix:')
        run: |
          echo "This is a bug fix"
          gh pr edit ${{ github.event.pull_request.number }} --add-label "bug"

  print-labels:
    name: Print labels
    runs-on: ubuntu-latest
    steps:
      - name: Print PR labels using join()
        run: |
          echo "PR labels:"
          echo ${{ join(github.event.pull_request.labels.*.name, ', ') }}
      
      - name: Print PR labels using toJSON()
        run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.labels) }}
          EOF

  status-checks:
    name: Status checks
    runs-on: ubuntu-latest
    steps:
      - name: Failing step
        run: exit 1
      - name: On success
        if: success()
        run: echo "Previous step succeeded"
      - name: On failure
        if: failure()
        run: echo "Previous step failed"
      - name: Always (unless cancelled)
        if: ${{ !cancelled() }}
        run: echo "The workflow wasn't cancelled"
      - name: On cancelled
        if: cancelled()
        run: echo "The workflow was cancelled"
