name: 11 - Working with Inputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: false
        description: 'Skip deployment'
      target:
        type: environment
        required: true
        description: 'Target environment'
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: 'Release to build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building ${{ inputs.tag }}"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !inputs.dry-run }}
    environment: ${{ inputs.target }}
    steps:
      - name: Deploy
        run: echo "Deploying ${{ inputs.tag }} to ${{ inputs.target }}"
        