name: 12 - Using Outputs

on: 
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      STATUS: ${{ steps.output.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo $GITHUB_OUTPUT
      - name: Build
        id: output
        run: echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.STATUS == 'success'
    steps:
      - name: Deploy
        run: echo "Deploying..."
  clean-up:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ !cancelled() }}
    steps:
      - name: Clean up
        run: echo "Cleaning up..."
